'use strict';

import Student from './Student.js';

(function () {
  const student1 = new Student('Vadim', 'Levadko', '25.05.2006');
  const student2 = new Student('Nikita', 'Byzko', '11.08.2006');
  const student3 = new Student('Mark', 'Turkulets', '25.03.2006');
  console.log(student1);
  student1.present();
  student1.mark(10);
  student1.present();
  student1.mark(8);
  student1.absent();
  student1.present();
  student1.mark(6);
  student1.present();
  student1.mark(2);
  student1.present();
  student1.mark(4);
  student1.present();
  student1.mark(7);
  student1.present();
  student1.mark(10);
  student1.present();
  student1.mark(10);
  student1.absent();
  console.log(student1.summary());

  student2.present();
  student2.mark(7);
  student2.present();
  student2.mark(3);
  student2.present();
  student2.present();
  student2.mark(10);
  student2.present();
  student2.mark(5);
  student2.present();
  student2.mark(9);
  student2.present();
  student2.present();
  student2.mark(2);
  student2.present();
  student2.mark(8);
  student2.absent();
  console.log(student2.summary());

  student3.present();
  student3.mark(10);
  student3.present();
  student3.mark(10);
  student3.present();
  student3.mark(10);
  student3.present();
  student3.mark(10);
  student3.present();
  student3.mark(10);
  student3.present();
  student3.mark(10);
  student3.present();
  student3.mark(10);
  student3.present();
  student3.mark(10);
  student3.present();
  student3.mark(10);
  student3.present();
  student3.mark(10);
  console.log(student3.summary());
}());
